name: cookpoint
description: CookPoint

publish_to: 'none'

version: 1.0.0+29

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  google_maps_flutter: ^2.0.1
  google_maps_flutter_web: ^0.2.1
  provider: ^4.3.2
  meta: ^1.3.0
  equatable: ^1.2.5
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  formz: ^0.3.2
  pedantic: ^1.11.0
  carousel_slider: ^3.0.0
  image_picker: ^0.7.3
  uuid: ^3.0.2
  dough: ^0.3.7
  url_launcher: ^6.0.2
  fluttertoast: ^8.0.3
  cached_network_image: ^2.5.1
  authentication_repository:
    path: packages/authentication_repository
  location_services:
    path: packages/location_services
  points_repository:
    path: packages/points_repository
  cookers_repository:
    path: packages/cookers_repository

dependency_overrides:
  intl: '>=0.17.0-nullsafety.2 <= 0.17.0-nullsafety.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/mini_marker@64.png
    - assets/images/mini_marker@128.png
    - assets/images/mini_marker@192.png
    - assets/images/mini_marker@256.png
    - assets/images/marker@64.png
    - assets/images/marker@128.png
    - assets/images/marker@192.png
    - assets/images/marker@256.png
