name: cookpoint
description: Cook Point flutter app.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^1.2.0
  location: ^3.2.4
  firebase_core: ^0.5.3
  firebase_storage: ^5.2.0
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  meta: ^1.3.0
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6
  bloc: ^6.1.1
  font_awesome_flutter: ^8.11.0
  formz: ^0.3.2
  pedantic: ^1.10.0
  image_picker: ^0.6.7+4
  image_cropper: ^1.3.1
  uuid: ^2.2.2
  authentication_repository:
    path: packages/authentication_repository
  accounts_repository:
    path: packages/accounts_repository
  products_repository:
    path: packages/products_repository

dependency_overrides:
  intl: '>=0.17.0-nullsafety.2 <= 0.17.0-nullsafety.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.4

flutter:

  uses-material-design: true