name: cookpoint
description: Cook Point flutter app.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.11.0
  google_maps_flutter: ^1.2.0
  firebase_core: ^0.5.1
  firebase_storage: ^5.0.1
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  meta: ^1.2.4
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6
  bloc: ^6.1.1
  formz: ^0.3.2
  pedantic: ^1.9.2
  sliding_sheet: ^0.4.1
  flutter_swiper: ^1.1.6
  authentication_repository:
    path: packages/authentication_repository
  location_services:
    path: packages/location_services
  orders_repository:
    path: packages/orders_repository
  points_repository:
    path: packages/points_repository
  products_repository:
    path: packages/products_repository
  profiles_repository:
    path: packages/profiles_repository

dependency_overrides:
  intl: '>=0.17.0-nullsafety.2 <= 0.17.0-nullsafety.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.4

flutter:
  uses-material-design: true