name: cookpoint
description: CookPoint

publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.11.0
  google_maps_flutter: ^1.2.0
  firebase_core: ^0.5.1
  firebase_storage: ^5.0.1
  provider: ^4.3.3
  meta: ^1.2.4
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6
  bloc: ^6.1.1
  formz: ^0.3.2
  pedantic: ^1.9.2
  carousel_slider: ^3.0.0
  image_picker: ^0.6.7+22
  uuid: ^2.2.2
  dough: ^0.3.7
  url_launcher: ^5.7.10
  android_intent: ^0.3.7+7
  fluttertoast: ^7.1.6
  cached_network_image: ^2.5.1
  authentication_repository:
    path: packages/authentication_repository
  location_services:
    path: packages/location_services
  points_repository:
    path: packages/points_repository
  cookers_repository:
    path: packages/cookers_repository

dependency_overrides:
  intl: '>=0.17.0-nullsafety.2 <= 0.17.0-nullsafety.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
  mockito: ^4.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logo_128px_128px.png
    - assets/images/logo_bold_192px_192px.png
