name: cookpoint
description: Food Here, There, Everywhere.

publish_to: 'none'

version: 1.0.0+44

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.0
  firebase_analytics: ^7.0.1
  google_maps_flutter: ^2.0.1
  provider: ^5.0.0
  meta: ^1.3.0
  equatable: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  formz: ^0.3.2
  pedantic: ^1.11.0
  carousel_slider: ^3.0.0
  image_picker: ^0.7.3
  uuid: ^3.0.2
  dough: ^1.0.1
  url_launcher: ^6.0.2
  fluttertoast: ^8.0.3
  cached_network_image: ^2.5.1
  image_cropper: ^1.4.0
  sliding_up_panel: ^1.0.2
  flutter_typeahead: ^3.1.1
  map_launcher: ^1.1.3
  line_awesome_flutter: ^1.0.1
  fuzzy: ^0.3.0
  authentication_repository:
    path: packages/authentication_repository
  location_services:
    path: packages/location_services
  points_repository:
    path: packages/points_repository
  cooks_repository:
    path: packages/cooks_repository

dependency_overrides:
  intl: '>=0.17.0-nullsafety.2 <= 0.17.0-nullsafety.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mockito: ^5.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/cover.png
    - assets/images/mini_marker_64.png
    - assets/images/mini_marker_128.png
    - assets/images/mini_marker_192.png
    - assets/images/mini_marker_256.png
    - assets/images/marker_64.png
    - assets/images/marker_128.png
    - assets/images/marker_192.png
    - assets/images/marker_256.png
