name: cookpoint
description: Cook Here, There, Everywhere.

publish_to: 'none'

version: 1.0.7+514

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  location_services:
    path: packages/location_services
  points_repository:
    path: packages/points_repository
  cooks_repository:
    path: packages/cooks_repository
  firebase_core: ^1.0.4
  firebase_storage: ^8.0.4
  firebase_analytics: ^8.0.1
  firebase_crashlytics: ^2.0.1
  google_maps_flutter: ^2.0.3
  provider: ^5.0.0
  meta: ^1.3.0
  equatable: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  formz: ^0.3.2
  pedantic: ^1.11.0
  carousel_slider: ^3.0.0
  image_picker: ^0.7.4
  uuid: ^3.0.0
  dough: ^1.0.1
  url_launcher: ^6.0.3
  map_launcher: ^2.0.0
  fluttertoast: ^8.0.6
  cached_network_image: ^3.0.0
  image_cropper: ^1.4.0
  sliding_up_panel: ^1.0.2
  flutter_typeahead: ^3.1.1
  line_awesome_flutter: ^1.0.1
  fuzzy: ^0.3.0
  connectivity: ^3.0.3
  shared_preferences: ^2.0.5
  package_info: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/cover.png
    - assets/images/mini_marker_64.png
    - assets/images/mini_marker_128.png
    - assets/images/mini_marker_192.png
    - assets/images/mini_marker_256.png
    - assets/images/marker_64.png
    - assets/images/marker_128.png
    - assets/images/marker_192.png
    - assets/images/marker_256.png

flutter_intl:
  enabled: true