name: points_repository

version: 1.0.0+5
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.4
  cloud_firestore: ^1.0.6
  geoflutterfire:
    path: packages/geoflutterfire
  equatable: ^2.0.0
  meta: ^1.3.0