/// Flutter icons CookPoint
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CookPoint
///      fonts:
///       - asset: fonts/CookPoint.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CookPoint {
  CookPoint._();

  static const _kFontFam = 'CookPoint';
  static const String _kFontPkg = null;

  static const IconData addPoint =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
