name: cooks_repository

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.2
  equatable: ^1.2.5
  meta: ^1.3.0
  lipsum: ^1.0.1