name: cooks_repository

version: 1.0.1+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.0.4
  cloud_firestore: ^1.0.6
  equatable: ^2.0.0
  meta: ^1.3.0
  lipsum: ^1.0.1